### ISSUE TITLE
[REQ] Visual Studio 2022 Version

### ISSUE THREAD

**Issue by dehghani-mehdi** [DarkDaskin/VSTabPath#7]
Is there any plan to make it work with VS2022?

**Comment by DarkDaskin** [comment]
Yes, I hope to find some time to work on it within a week or two.

**Comment by Eddie-cz** [comment]
Bump

**Comment by DarkDaskin** [comment]
Added support for VS 2022.

Since supporting multiple VS versions turned out to be non-trivial anyway, I spent some time to find another solution which allowed to keep single VSIX file.
